name: D4L Utils CI (PR testing)

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Display runner context
      run: hostname -s
    - uses: actions/checkout@v2
    - name: Cache ruby gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
    - name: Reset iOS simulators (Required to avoid tests failing problem)
      run: xcrun simctl erase all
    - name: test
      run: bundle exec fastlane test
    - name: Create sonarqube report
      run: ./generate-cov-report.sh build/DerivedData/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: sonarqube-generic-coverage.xml

  code-coverage:
    name: Code Coverage Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
